#############################################################################
# Makefile for building: rockbot_dreamcast.elf
# Generated by qmake (2.01a) (Qt 4.8.4) on: ter nov 12 15:47:58 2013
# Project:  cpp_rockbot.pro
# Template: app
# Command: /usr/lib/i386-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile cpp_rockbot.pro
#############################################################################

####### Compiler, tools and options

CC            = /opt/toolchains/dc/sh-elf/bin/sh-elf-gcc
CXX           = /opt/toolchains/dc/sh-elf/bin/sh-elf-g++
DEFINES       = 
CFLAGS        = -pipe -g -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -I$(KOS_BASE)/addons/include $(OPTFLAGS) $(KOS_LDFLAGS) -Wall -O2 -DHANDHELD -g -I. -I/home/iuri/devel/SDK/Dreamcast/kos/utils/dc-chain/newlib-2.0.0/newlib/libc/include -I/opt/toolchains/dc/sh-elf/include -DDREAMCAST $(OBJEXTRA) $(KOS_LIBS) -g -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I.
LINK          = /opt/toolchains/dc/sh-elf/bin/sh-elf-g++
LFLAGS        = 
LIBS          = $(SUBLIBS)   $(KOS_LIBS) $(KOS_LDFLAGS) -L. -L/home/iuri/devel/SDK/Dreamcast/kos/addons/lib/dreamcast/ -lm -lgcc -lstdc++ -lc -lSDL_ttf -lSDL_mixer_126 -lSDL_image_124 -lSDL_1213 -ljpeg -lpng -lfreetype -lz_123 $(OBJEXTRA) 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/i386-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		character/character.cpp \
		graphicslib.cpp \
		inputlib.cpp \
		game.cpp \
		stage.cpp \
		classmap.cpp \
		character/classplayer.cpp \
		timerlib.cpp \
		sceneslib.cpp \
		soundlib.cpp \
		projectilelib.cpp \
		character/classnpc.cpp \
		stage_select.cpp \
		class_config.cpp \
		objects/object.cpp \
		class_colorcycle.cpp \
		graphic/option_picker.cpp \
		scenes/dialogs.cpp \
		file/file_io.cpp \
		character/classboss.cpp \
		graphic/animation.cpp \
		scenes/ending.cpp \
		colision_detection.cpp \
		character/artificial_inteligence.cpp \
		options/key_map.cpp \
		graphic/draw.cpp \
		aux_tools/trajectory_parabola.cpp \
		file/convert.cpp 
OBJECTS       = main.o \
		character.o \
		graphicslib.o \
		inputlib.o \
		game.o \
		stage.o \
		classmap.o \
		classplayer.o \
		timerlib.o \
		sceneslib.o \
		soundlib.o \
		projectilelib.o \
		classnpc.o \
		stage_select.o \
		class_config.o \
		object.o \
		class_colorcycle.o \
		option_picker.o \
		dialogs.o \
		file_io.o \
		classboss.o \
		animation.o \
		ending.o \
		colision_detection.o \
		artificial_inteligence.o \
		key_map.o \
		draw.o \
		trajectory_parabola.o \
		convert.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		cpp_rockbot.pro
QMAKE_TARGET  = rockbot_dreamcast.elf
DESTDIR       = 
TARGET        = rockbot_dreamcast.elf

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: cpp_rockbot.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile cpp_rockbot.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile cpp_rockbot.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/rockbot_dreamcast.elf1.0.0 || $(MKDIR) .tmp/rockbot_dreamcast.elf1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/rockbot_dreamcast.elf1.0.0/ && (cd `dirname .tmp/rockbot_dreamcast.elf1.0.0` && $(TAR) rockbot_dreamcast.elf1.0.0.tar rockbot_dreamcast.elf1.0.0 && $(COMPRESS) rockbot_dreamcast.elf1.0.0.tar) && $(MOVE) `dirname .tmp/rockbot_dreamcast.elf1.0.0`/rockbot_dreamcast.elf1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/rockbot_dreamcast.elf1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp graphicslib.h \
		defines.h \
		st_common.h \
		class_colorcycle.h \
		file/file_io.h \
		file/format.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		graphic/draw.h \
		inputlib.h \
		timerlib.h \
		soundlib.h \
		game.h \
		character/classplayer.h \
		character/character.h \
		st_characterState.h \
		st_teleporter.h \
		st_projectile.h \
		st_platform.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		sceneslib.h \
		stage.h \
		classmap.h \
		objects/object.h \
		graphic/animation.h \
		class_config.h \
		scenes/dialogs.h \
		scenes/ending.h \
		ports/ps2/modules.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

character.o: character/character.cpp character/character.h \
		st_hitPoints.h \
		st_common.h \
		st_characterState.h \
		st_teleporter.h \
		st_projectile.h \
		st_platform.h \
		defines.h \
		graphicslib.h \
		class_colorcycle.h \
		file/file_io.h \
		file/format.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		projectilelib.h \
		timerlib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		game.h \
		character/classplayer.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		sceneslib.h \
		stage.h \
		classmap.h \
		objects/object.h \
		graphic/animation.h \
		class_config.h \
		scenes/dialogs.h \
		soundlib.h \
		inputlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o character.o character/character.cpp

graphicslib.o: graphicslib.cpp defines.h \
		inputlib.h \
		file/format.h \
		st_common.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		timerlib.h \
		soundlib.h \
		graphicslib.h \
		class_colorcycle.h \
		file/file_io.h \
		class_config.h \
		character/classplayer.h \
		character/character.h \
		st_characterState.h \
		st_teleporter.h \
		st_projectile.h \
		st_platform.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		character/classnpc.h \
		character/artificial_inteligence.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphicslib.o graphicslib.cpp

inputlib.o: inputlib.cpp inputlib.h \
		defines.h \
		file/format.h \
		st_common.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		timerlib.h \
		graphicslib.h \
		class_colorcycle.h \
		file/file_io.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inputlib.o inputlib.cpp

game.o: game.cpp game.h \
		character/classplayer.h \
		character/character.h \
		st_hitPoints.h \
		st_common.h \
		st_characterState.h \
		st_teleporter.h \
		st_projectile.h \
		st_platform.h \
		defines.h \
		graphicslib.h \
		class_colorcycle.h \
		file/file_io.h \
		file/format.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		projectilelib.h \
		timerlib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		sceneslib.h \
		stage.h \
		classmap.h \
		objects/object.h \
		graphic/animation.h \
		class_config.h \
		scenes/dialogs.h \
		soundlib.h \
		inputlib.h \
		scenes/ending.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game.o game.cpp

stage.o: stage.cpp file/file_io.h \
		file/format.h \
		defines.h \
		st_common.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		stage.h \
		classmap.h \
		graphicslib.h \
		class_colorcycle.h \
		character/classnpc.h \
		character/character.h \
		st_characterState.h \
		st_teleporter.h \
		st_projectile.h \
		st_platform.h \
		projectilelib.h \
		timerlib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		character/artificial_inteligence.h \
		objects/object.h \
		graphic/animation.h \
		character/classplayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stage.o stage.cpp

classmap.o: classmap.cpp classmap.h \
		defines.h \
		st_common.h \
		graphicslib.h \
		class_colorcycle.h \
		file/file_io.h \
		file/format.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		character/classnpc.h \
		character/character.h \
		st_characterState.h \
		st_teleporter.h \
		st_projectile.h \
		st_platform.h \
		projectilelib.h \
		timerlib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		character/artificial_inteligence.h \
		objects/object.h \
		graphic/animation.h \
		character/classboss.h \
		colision_detection.h \
		game.h \
		character/classplayer.h \
		sceneslib.h \
		stage.h \
		class_config.h \
		scenes/dialogs.h \
		inputlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classmap.o classmap.cpp

classplayer.o: character/classplayer.cpp character/classplayer.h \
		character/character.h \
		st_hitPoints.h \
		st_common.h \
		st_characterState.h \
		st_teleporter.h \
		st_projectile.h \
		st_platform.h \
		defines.h \
		graphicslib.h \
		class_colorcycle.h \
		file/file_io.h \
		file/format.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		projectilelib.h \
		timerlib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		inputlib.h \
		class_config.h \
		soundlib.h \
		game.h \
		sceneslib.h \
		stage.h \
		classmap.h \
		objects/object.h \
		graphic/animation.h \
		scenes/dialogs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classplayer.o character/classplayer.cpp

timerlib.o: timerlib.cpp timerlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timerlib.o timerlib.cpp

sceneslib.o: sceneslib.cpp sceneslib.h \
		defines.h \
		graphicslib.h \
		st_common.h \
		class_colorcycle.h \
		file/file_io.h \
		file/format.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		soundlib.h \
		inputlib.h \
		graphic/draw.h \
		stage_select.h \
		timerlib.h \
		graphic/option_picker.h \
		options/key_map.h \
		graphic/animation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sceneslib.o sceneslib.cpp

soundlib.o: soundlib.cpp soundlib.h \
		defines.h \
		file/format.h \
		st_common.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o soundlib.o soundlib.cpp

projectilelib.o: projectilelib.cpp projectilelib.h \
		st_common.h \
		defines.h \
		timerlib.h \
		graphicslib.h \
		class_colorcycle.h \
		file/file_io.h \
		file/format.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		classmap.h \
		character/classnpc.h \
		character/character.h \
		st_characterState.h \
		st_teleporter.h \
		st_projectile.h \
		st_platform.h \
		character/artificial_inteligence.h \
		objects/object.h \
		graphic/animation.h \
		soundlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectilelib.o projectilelib.cpp

classnpc.o: character/classnpc.cpp character/classnpc.h \
		character/character.h \
		st_hitPoints.h \
		st_common.h \
		st_characterState.h \
		st_teleporter.h \
		st_projectile.h \
		st_platform.h \
		defines.h \
		graphicslib.h \
		class_colorcycle.h \
		file/file_io.h \
		file/format.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		projectilelib.h \
		timerlib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		character/artificial_inteligence.h \
		stage.h \
		classmap.h \
		objects/object.h \
		graphic/animation.h \
		character/classplayer.h \
		inputlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classnpc.o character/classnpc.cpp

stage_select.o: stage_select.cpp stage_select.h \
		graphicslib.h \
		defines.h \
		st_common.h \
		class_colorcycle.h \
		file/file_io.h \
		file/format.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		inputlib.h \
		timerlib.h \
		soundlib.h \
		graphic/draw.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stage_select.o stage_select.cpp

class_config.o: class_config.cpp class_config.h \
		st_common.h \
		character/classplayer.h \
		character/character.h \
		st_hitPoints.h \
		st_characterState.h \
		st_teleporter.h \
		st_projectile.h \
		st_platform.h \
		defines.h \
		graphicslib.h \
		class_colorcycle.h \
		file/file_io.h \
		file/format.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		projectilelib.h \
		timerlib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		inputlib.h \
		soundlib.h \
		game.h \
		sceneslib.h \
		stage.h \
		classmap.h \
		objects/object.h \
		graphic/animation.h \
		scenes/dialogs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o class_config.o class_config.cpp

object.o: objects/object.cpp objects/object.h \
		graphicslib.h \
		defines.h \
		st_common.h \
		class_colorcycle.h \
		file/file_io.h \
		file/format.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		classmap.h \
		character/classnpc.h \
		character/character.h \
		st_characterState.h \
		st_teleporter.h \
		st_projectile.h \
		st_platform.h \
		projectilelib.h \
		timerlib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		character/artificial_inteligence.h \
		graphic/animation.h \
		soundlib.h \
		game.h \
		character/classplayer.h \
		sceneslib.h \
		stage.h \
		class_config.h \
		scenes/dialogs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object.o objects/object.cpp

class_colorcycle.o: class_colorcycle.cpp class_colorcycle.h \
		defines.h \
		st_common.h \
		file/file_io.h \
		file/format.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		timerlib.h \
		graphicslib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o class_colorcycle.o class_colorcycle.cpp

option_picker.o: graphic/option_picker.cpp graphic/option_picker.h \
		st_common.h \
		soundlib.h \
		defines.h \
		graphicslib.h \
		class_colorcycle.h \
		file/file_io.h \
		file/format.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		inputlib.h \
		graphic/draw.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o option_picker.o graphic/option_picker.cpp

dialogs.o: scenes/dialogs.cpp scenes/dialogs.h \
		defines.h \
		st_common.h \
		file/format.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		graphicslib.h \
		class_colorcycle.h \
		file/file_io.h \
		inputlib.h \
		graphic/draw.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogs.o scenes/dialogs.cpp

file_io.o: file/file_io.cpp file/file_io.h \
		file/format.h \
		defines.h \
		st_common.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		file/convert.h \
		timerlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o file_io.o file/file_io.cpp

classboss.o: character/classboss.cpp character/classboss.h \
		character/classnpc.h \
		character/character.h \
		st_hitPoints.h \
		st_common.h \
		st_characterState.h \
		st_teleporter.h \
		st_projectile.h \
		st_platform.h \
		defines.h \
		graphicslib.h \
		class_colorcycle.h \
		file/file_io.h \
		file/format.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		projectilelib.h \
		timerlib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		character/artificial_inteligence.h \
		classmap.h \
		objects/object.h \
		graphic/animation.h \
		scenes/dialogs.h \
		game.h \
		character/classplayer.h \
		sceneslib.h \
		stage.h \
		class_config.h \
		soundlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classboss.o character/classboss.cpp

animation.o: graphic/animation.cpp graphic/animation.h \
		st_common.h \
		graphicslib.h \
		defines.h \
		class_colorcycle.h \
		file/file_io.h \
		file/format.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		timerlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animation.o graphic/animation.cpp

ending.o: scenes/ending.cpp scenes/ending.h \
		graphicslib.h \
		defines.h \
		st_common.h \
		class_colorcycle.h \
		file/file_io.h \
		file/format.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		soundlib.h \
		inputlib.h \
		timerlib.h \
		game.h \
		character/classplayer.h \
		character/character.h \
		st_characterState.h \
		st_teleporter.h \
		st_projectile.h \
		st_platform.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		sceneslib.h \
		stage.h \
		classmap.h \
		objects/object.h \
		graphic/animation.h \
		class_config.h \
		scenes/dialogs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ending.o scenes/ending.cpp

colision_detection.o: colision_detection.cpp colision_detection.h \
		st_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colision_detection.o colision_detection.cpp

artificial_inteligence.o: character/artificial_inteligence.cpp character/artificial_inteligence.h \
		character/character.h \
		st_hitPoints.h \
		st_common.h \
		st_characterState.h \
		st_teleporter.h \
		st_projectile.h \
		st_platform.h \
		defines.h \
		graphicslib.h \
		class_colorcycle.h \
		file/file_io.h \
		file/format.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		projectilelib.h \
		timerlib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		classmap.h \
		character/classnpc.h \
		objects/object.h \
		graphic/animation.h \
		character/classplayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o artificial_inteligence.o character/artificial_inteligence.cpp

key_map.o: options/key_map.cpp options/key_map.h \
		graphicslib.h \
		defines.h \
		st_common.h \
		class_colorcycle.h \
		file/file_io.h \
		file/format.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		inputlib.h \
		soundlib.h \
		graphic/draw.h \
		graphic/option_picker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o key_map.o options/key_map.cpp

draw.o: graphic/draw.cpp graphic/draw.h \
		graphicslib.h \
		defines.h \
		st_common.h \
		class_colorcycle.h \
		file/file_io.h \
		file/format.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h \
		timerlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o draw.o graphic/draw.cpp

trajectory_parabola.o: aux_tools/trajectory_parabola.cpp aux_tools/trajectory_parabola.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trajectory_parabola.o aux_tools/trajectory_parabola.cpp

convert.o: file/convert.cpp file/convert.h \
		file/file_io.h \
		file/format.h \
		defines.h \
		st_common.h \
		st_hitPoints.h \
		file/v_2_1_1.h \
		file/v_2_0_0.h \
		file/v_2_0_4.h \
		file/v_2_0_3.h \
		file/v_2_0_2.h \
		file/v_2_0_1.h \
		file/v_2_1.h \
		file/v_2_1_2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o convert.o file/convert.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

